########################################
# Application
########################################

spring.application.name=HireSmart

server.port=8080

########################################
# MySQL Database Configuration
########################################

spring.datasource.url=jdbc:mysql://localhost:3306/hiresmart_db
spring.datasource.username=root
spring.datasource.password=Cartoon238912
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

########################################
# JPA / Hibernate
########################################

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

########################################
# File Upload
########################################

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

########################################
# Logging
########################################

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
########################################
# File Upload Path
########################################

file.upload-dir=uploads/resumes